[tools]
rojo = "rojo-rbx/rojo@7.3.0"
wally = "UpliftGames/wally@0.3.2"
stylua = "johnnymorganz/stylua@0.18.1"
selene = "Kampfkarren/selene@0.25.0"
luau-lsp = "johnnymorganz/luau-lsp@1.22.1"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
